name: Web Unit & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit:
    name: Vitest Unit (web) + Coverage
    runs-on: ubuntu-latest

    env:
      # Supabase env if unit tests import clients; harmless if unused
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests (Vitest) with coverage
        run: pnpm turbo run test --filter web

      - name: Upload coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: web-coverage
          path: apps/web/coverage/
          if-no-files-found: warn
